build:
	pandoc --filter pandoc-citeproc --bibliography=sinkhole_privacy_preserving_dht.bib --variable classoption=twocolumn --variable papersize=a4paper sinkhole_privacy_preserving_dht.md -o sinkhole_privacy_preserving_dht.pdf
